name: build-master
on:
  push:
    branches: [ master ]
jobs:
  build_master:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    env:
      FILENAME: main.tex
      BIB_FILENAME: main.aux
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        run: |
          cd thesis
          pdflatex -interaction=nonstopmode $FILENAME && \
          bibtex $BIB_FILENAME && \
          pdflatex -interaction=nonstopmode -output-directory=.. $FILENAME
          cd ..
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE }}
          upload-from: ./main.pdf
          upload-to: '/thesis/thesis-master'
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
